apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: ${namespace}

spec:
  selector:
    app: ${appLabel}
  ports:
    - port: ${port}
      targetPort: ${targetPort}
      protocol: TCP
  type: LoadBalancer
